Repository InformedSolutions/JAQU-CAZ-Retrofit-API, pull requests merged in 2021-02, with the labels that each got.

#203 [CAZB-4063] Upgrade Terraform version in pipeline
  .drone.yml
  .drone2.yml
Labels: bug

#202 Promote Retrofit v1.8.0 to Production
  .github/dependabot.yml
  pom.xml
  src/it/java/uk/gov/caz/retrofit/controller/HistoricalInfoControllerIT.java
  src/it/java/uk/gov/caz/retrofit/controller/RetrofitVehicleControllerTestIT.java
  src/it/java/uk/gov/caz/retrofit/repository/RetrofittedVehiclePostgresRepositoryTestIT.java
  src/it/resources/data/sql/add-sample-audit-data.sql
  src/main/java/uk/gov/caz/retrofit/controller/RetrofitVehicleController.java
  src/main/java/uk/gov/caz/retrofit/dto/RetrofitInfoHistoricalRequest.java
  src/main/java/uk/gov/caz/retrofit/dto/RetrofitStatusResponse.java
  src/main/java/uk/gov/caz/retrofit/model/RetrofitStatus.java
  src/main/java/uk/gov/caz/retrofit/repository/RetrofitVehicleHistoryPostgresRepository.java
  src/main/java/uk/gov/caz/retrofit/repository/RetrofittedVehiclePostgresRepository.java
  src/main/java/uk/gov/caz/retrofit/service/RetrofitHistoricalInfoService.java
  src/main/java/uk/gov/caz/retrofit/service/RetrofitVehicleService.java
  src/test/java/uk/gov/caz/retrofit/service/RegisterServiceTest.java
  src/test/java/uk/gov/caz/retrofit/service/RetrofitVehicleServiceTest.java
Labels: Retro v1.8.0, release

#204 Promote Retrofit v1.8.1 to Pre-Prod
  .drone.yml
  .drone2.yml
Labels: release

#205 Promote Retrofit v1.8.1 to Production
  .drone.yml
  .drone2.yml
Labels: Retro v1.8.1, release
